### ISSUE TITLE
Variable Dates for Annual Events

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/LGBTQ-of-the-day-bot#246]
**Is your feature request related to a problem? Please describe.**
#238 is for adding annual events to `words_dir/tweet_annual_events.py`. However, many of these annual events fall on variable days each year.

https://github.com/VickiLanger/LGBTQ-of-the-day-bot/pull/243#issue-511955808

**Describe the solution you'd like**
Be able to add events with variable dates like `3rd tuesday of march` in an as easy as possible manner to keep this repo #CodeNewbie friendly

**Describe alternatives you've considered**

**Additional context**
Current files: 
- list of events https://github.com/VickiLanger/LGBTQ-of-the-day-bot/blob/production/words_dir/tweet_annual_events.py
- tweet function https://github.com/VickiLanger/LGBTQ-of-the-day-bot/blob/production/tweet_annual_days.py

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
```
2020-10-30T12:05:51.782186+00:00 app[scheduler.3826]: Traceback (most recent call last):
2020-10-30T12:05:51.782211+00:00 app[scheduler.3826]:   File "tweet_annual_days.py", line 58, in <module>
2020-10-30T12:05:51.782639+00:00 app[scheduler.3826]:     tweet_annual_event()
2020-10-30T12:05:51.782702+00:00 app[scheduler.3826]:   File "tweet_annual_days.py", line 52, in tweet_annual_event
2020-10-30T12:05:51.782962+00:00 app[scheduler.3826]:     event_tweet = tweet_template + list_of_event_tweets[0]
2020-10-30T12:05:51.783058+00:00 app[scheduler.3826]: TypeError: must be str, not list
```
